name: Build and upload to PyPI

on:
  push:
    branches:
      - 'release-next'
permissions:
  contents: write

jobs:
  update_version:
    name: update version
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: Update version on merge
        run: |
            python tools/version.py "minor"
      - name: Store changes
        uses: actions/upload-artifact@v3
        with:
          name: setup
          path: setup.py


  update_setup:
    needs: [update_version]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout_release
        if: ${{ github.event.push.head.ref }} == 'release-next'
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          repository: ${{github.event.push.head.repo.full_name }}
          ref: ${{ github.event.push.head.ref }}
 
      - uses: actions/download-artifact@v3
        with:
          name: setup
      - name: check
        run: |
          cat setup.py
          echo ${{github.event.merge_group.head.repo.full_name }}
      - name: Commit on merge
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add setup.py
          git commit -m "update version number"
          git push
      - name: create_new_branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout --no-track -b version_bump origin/release-next
          git push --set-upstream origin version_bump
